on:
  pull_request:
    types: [reopened, opened, synchronize, edited]

name: Create PR Env
jobs:
  create_or_update_pr_env:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install Dependencies
        run: npm ci
      - name: Build Site
        run: npm run build
      - name: Deploy to AWS CloudFormation
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: S3 on-demand enviroment
          template: cloudformation/on-demand-environment.yml
          parameter-overrides: "EnvPrefix=${{ env.BRANCH_NAME }},BucketName=${{ env.BUCKET_NAME }},Username=${{ env.USERNAME }}"
      - name: Deploy static site to S3 bucket
        run: aws s3 sync ./dist s3://${{ env.BRANCH_NAME }}.${{ env.USERNAME }}.com
      - run: node .github/actions/comment.js
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      BUCKET_NAME: ${{ secrets.BUCKET_NAME }}
      BRANCH_NAME: ${{ github.head_ref }}
      USERNAME: ${{ github.actor }}
      
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      ISSUE_NUMBER: ${{ github.event.pull_request.number }}
      REPO: 'jkrsp'
      OWNER: ${{ github.repository_owner }}
      WEBSITE_LINK: ${{ steps.env-name.outputs.environment }}