
on:
  pull_request:
    types: [reopened, opened]

name: Create S3 Bucket
jobs:
  create_or_update_pr_env:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Deploy to AWS CloudFormation
        id: cfn-deploy
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: ${{ env.BRANCH_NAME }}
          template: cloudformation/on-demand-environment.yml
          parameter-overrides: "EnvPrefix=${{ env.BRANCH_NAME }},BucketName=${{ env.BUCKET_NAME }},Username=${{ env.USERNAME }}"
          aws-region: ${{ env.AWS_REGION }}
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      BUCKET_NAME: '${{ github.head_ref }}.${{ github.actor }}.com'
      AWS_REGION: ${{ secrets.AWS_REGION }}
      BRANCH_NAME: ${{ github.head_ref }}
      USERNAME: ${{ github.actor }}
